### ISSUE TITLE
SimpleMappingHandlerMethodExceptionResolver 添加异常日志输出

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-spring#171]
SimpleMappingHandlerMethodExceptionResolver 添加异常日志输出

**Comment by venusdrogon** [comment]
```JAVA

16:00:27 ERROR (SimpleMappingHandlerMethodExceptionResolver.java:112) doResolveHandlerMethodException() - [UnexWorldpayNotifyController.handler()],viewName:[printwrite:STOP]
java.lang.NullPointerException: null
	at com.feilong.store.nebula.pay.query.StoreTradeDataQuery.buildTradeData(StoreTradeDataQuery.java:123)
	at com.feilong.store.nebula.pay.query.StoreTradeDataQuery.query(StoreTradeDataQuery.java:109)
	at com.feilong.psi.controller.notify.handler.DefaultNotifyHandler.handler(DefaultNotifyHandler.java:103)
	at com.feilong.psi.unex.controller.notify.UnexWorldpayNotifyController.handler(UnexWorldpayNotifyController.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:853)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)


```
