### ISSUE TITLE
com.feilong.spring.web.util.WebSpringUtil.getBean(ServletContext, String) 注释可能有bug

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-spring#9]
com.feilong.spring.web.util.WebSpringUtil.getBean(ServletContext, String) 注释可能有bug

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/28710146-883d10ae-73b5-11e7-8da8-46f2983aa494.png)

**Comment by venusdrogon** [comment]
```JAVA


17:05:18 ERROR (HypePdpController.java:253) call() - 
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.feilong.captcha.manager.rule.RuleResolver] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:296)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:293)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1131)
	at com.feilong.spring.web.util.WebSpringUtil.getBean(WebSpringUtil.java:266)
	at com.feilong.spring.web.util.WebSpringUtil.getBean(WebSpringUtil.java:162)
	at com.feilong.captcha.manager.validateneedable.DefaultValidateNeedable.needValidate(DefaultValidateNeedable.java:68)
	at com.feilong.captcha.manager.CaptchaUtil.validate(CaptchaUtil.java:209)
	at com.baozun.store.web.controller.hypepdp.HypePdpController$2.call(HypePdpController.java:232)
	at com.baozun.store.web.controller.hypepdp.HypePdpController$2.call(HypePdpController.java:209)
	at org.springframework.web.context.request.async.WebAsyncManager$4.run(WebAsyncManager.java:313)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by venusdrogon** [comment]
```JAVA

17:13:45 ERROR (HypePdpController.java:253) call() - 
java.lang.NullPointerException: null
	at org.apache.catalina.connector.Request.getServletContext(Request.java:1664)
	at org.apache.catalina.connector.RequestFacade.getServletContext(RequestFacade.java:1018)
	at javax.servlet.ServletRequestWrapper.getServletContext(ServletRequestWrapper.java:352)
	at com.feilong.spring.web.util.WebSpringUtil.getWebApplicationContext(WebSpringUtil.java:320)
	at com.feilong.spring.web.util.WebSpringUtil.getBean(WebSpringUtil.java:161)
	at com.feilong.captcha.manager.validateneedable.DefaultValidateNeedable.needValidate(DefaultValidateNeedable.java:68)
	at com.feilong.captcha.manager.CaptchaUtil.validate(CaptchaUtil.java:209)
	at com.baozun.store.web.controller.hypepdp.HypePdpController$2.call(HypePdpController.java:232)
	at com.baozun.store.web.controller.hypepdp.HypePdpController$2.call(HypePdpController.java:209)
	at org.springframework.web.context.request.async.WebAsyncManager$4.run(WebAsyncManager.java:313)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17:13:45 INFO  (HypePdpController.java:256) call() - [retrieveSecretKey] endtime:1501233225393


```

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/28711450-2eb1c020-73ba-11e7-9410-5012ae569f6e.png)

**Comment by venusdrogon** [comment]
spring  org.springframework.mock.web.MockHttpServletRequest.getServletContext()

有个提示 `(Not  available in the standard HttpServletRequest interface for some reason.)`



```JAVA

/**
	 * Return the ServletContext that this request is associated with. (Not
	 * available in the standard HttpServletRequest interface for some reason.)
	 */
	public ServletContext getServletContext() {
		return this.servletContext;
	}

```
